version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    volumes:
       - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS: -Xmx256m -Xms256m"
      - node.name=elasticsearch
      - network.host=0.0.0.0
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.1
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./pipeline:/usr/share/logstash/pipeline:ro
      - /var/log/GDPR/myapplication:/var/log/GDPR/myapplication:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.1
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://localhost:9201

    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local