## Save in: kibana/config/kibana.yml
# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0"
elasticsearch.hosts: ['http://elasticsearch:9201','http://elasticsearch:9200']
elasticsearch.username: elastic
elasticsearch.password: changeme